iptables -I INPUT -p tcp  --dport 3013 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 3013 -j DROP &>/dev/null
iptables -I INPUT -p udp  --dport 111 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 111 -j DROP &>/dev/null
iptables -I INPUT -p udp  --dport 8011 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 8011 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 8080 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 8080 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 1112 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 1112 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 11443 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 11443 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 80 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 80 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 18081 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 18081 -j DROP &>/dev/null
iptables -I INTPUT -p tcp  --dport 443 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 443 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 20001 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 20001 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 81 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 81 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 11038 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 11038 -j DROP &>/dev/null
iptables -I INTPUT -p tcp  --dport 8086 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 8086 -j DROP &>/dev/null
iptables -I INTPUT -p tcp  --dport 8088 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 8088 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 443 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 443 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 10012 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 10012 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 8085 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 8085 -j DROP &>/dev/null
iptables -I INTPUT -p tcp  --dport 9030 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 9030 -j DROP &>/dev/null
iptables -I INTPUT -p tcp  --dport 9031 -j DROP &>/dev/null
iptables -I OUTPUT -p tcp  --dport 9031 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 9030 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 9030 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 9031 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 9031 -j DROP &>/dev/null
iptables -I INTPUT -p udp  --dport 443 -j DROP &>/dev/null
iptables -I OUTPUT -p udp  --dport 443 -j DROP &>/dev/null
iptables -I INPUT -p tcp  --dport 443 -j REJECT &>/dev/null